# Generated by Django 4.1 on 2025-12-09 16:27

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_id", models.IntegerField(unique=True)),
                ("status", models.CharField(max_length=20)),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("reason", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "db_table": "payment_service_payments",
            },
        ),
        migrations.CreateModel(
            name="PaymentInbox",
            fields=[
                (
                    "message_id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                ("payload", models.JSONField()),
            ],
            options={
                "db_table": "payment_service_inbox",
            },
        ),
    ]
