# Generated by Django 4.1 on 2025-12-09 16:33

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Shipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_id", models.IntegerField(unique=True)),
                ("tracking_number", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "db_table": "shipping_service_shipments",
            },
        ),
        migrations.CreateModel(
            name="ShippingInbox",
            fields=[
                (
                    "message_id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                ("payload", models.JSONField()),
            ],
            options={
                "db_table": "shipping_service_inbox",
            },
        ),
    ]
